# generated by datamodel-codegen:
#   filename:  author_entries.json
#   timestamp: 2021-02-28T18:11:23+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class TopicTitle(BaseModel):
    Title: Optional[str]
    Kind: Optional[str]


class TopicId(BaseModel):
    Id: int
    TopicTitle: TopicTitle
    Title: Optional[str]


class Author(BaseModel):
    Nick: Optional[str]
    Id: int


class EntryContent(BaseModel):
    Id: int
    Content: Optional[str]
    Author: Author
    Created: Optional[str]
    LastUpdated: Optional[str]
    IsFavorite: bool
    FavoriteCount: int
    Hidden: bool
    Active: bool
    CommentCount: int
    CommentSummary: Optional[dict]
    AvatarUrl: Optional[str]
    TopicId: Optional[int]
    TopicTitle: Optional[str]


class Entry(BaseModel):
    TopicId: TopicId
    Entry: EntryContent


class Data(BaseModel):
    PinnedEntry: Optional[dict]
    Entries: List[Entry]
    PageCount: int
    PageSize: int
    PageIndex: int


class AuthorEntries(BaseModel):
    Success: Optional[bool]
    Message: Optional[str]
    Data: Optional[Data]
